# Generated by Django 3.2.16 on 2022-11-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('reference', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('qte_stock', models.DecimalField(decimal_places=3, max_digits=30)),
                ('valeur_initial', models.DecimalField(decimal_places=3, max_digits=30)),
                ('valeur_actuel', models.DecimalField(decimal_places=3, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.DecimalField(decimal_places=3, max_digits=30)),
                ('value', models.DecimalField(decimal_places=3, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('in_out', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='products.product')),
            ],
        ),
    ]
