# Generated by Django 3.2.16 on 2022-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221108_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-update_at', '-value', '-qte_stock')},
        ),
        migrations.AddField(
            model_name='product',
            name='qte_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='value_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
