# Generated by Django 3.2.16 on 2022-11-10 10:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20221110_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qte_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
