# Generated by Django 3.2.16 on 2022-11-10 12:25

import apps.products.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20221110_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qte_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=apps.products.storage.OverwriteStorage(location=pathlib.PureWindowsPath('C:/Projects/product_tracker/media')), upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='value_picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=apps.products.storage.OverwriteStorage(location=pathlib.PureWindowsPath('C:/Projects/product_tracker/media')), upload_to=''),
        ),
    ]
