# Generated by Django 3.2.16 on 2022-11-16 03:12

import apps.products.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20221110_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qte_picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_picture',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=apps.products.storage.OverwriteStorage(location=pathlib.PureWindowsPath('C:/Projects/python/product_tracker/media')), upload_to=''),
        ),
    ]
