# Generated by Django 3.2.16 on 2022-11-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221116_0412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
