# Generated by Django 3.2.16 on 2022-11-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_movement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unite',
            field=models.CharField(choices=[('t', 'Tonne'), ('kg', 'Kg')], default='t', max_length=2),
        ),
    ]
