# Generated by Django 3.2.16 on 2022-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('reference', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('date_range', models.CharField(max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=30)),
                ('previous_value', models.DecimalField(decimal_places=3, max_digits=30)),
            ],
        ),
    ]
