# Generated by Django 3.2.16 on 2022-11-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaissements', '0002_encaissement_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('remarque', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('sender', models.CharField(max_length=15, null=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('confirm', models.BooleanField()),
            ],
        ),
    ]
