# Generated by Django 3.2.16 on 2022-11-22 03:11

import apps.encaissements.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('encaissements', '0003_facturecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissement',
            name='picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=apps.encaissements.storage.OverwriteStorage(location=pathlib.PureWindowsPath('c:/Projects/python/product_tracker/media')), upload_to=''),
        ),
        migrations.AddField(
            model_name='facturecharge',
            name='picture',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=apps.encaissements.storage.OverwriteStorage(location=pathlib.PureWindowsPath('c:/Projects/python/product_tracker/media')), upload_to=''),
        ),
    ]
