# Generated by Django 3.2.16 on 2022-11-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaissements', '0004_auto_20221122_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaissement',
            name='picture',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='facturecharge',
            name='picture',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=''),
        ),
    ]
