# Generated by Django 3.2.16 on 2022-11-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encaissements', '0005_auto_20221122_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturecharge',
            name='entity',
            field=models.CharField(choices=[('P', 'PROMAG'), ('INF', 'INFRABITUM')], default='INF', max_length=5),
        ),
    ]
